name: "Hello Actions"
description: "Greet someone"
author: "crguezl@ull.edu.es"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "Procesadores de Lenguajes"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
